#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use Mail::Milter::Authentication;

my $connection = 'inet:12345@localhost';

GetOptions (
    'connection=s' => \$connection,
) or die show_usage();

sub show_usage {
    return join( "\n",
        'Usage:',
        'authentication_milter connection=inet:1234@localhost'
    );
}

Mail::Milter::Authentication::start({
    'connection' => $connection,
});

